swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
  /account/{id}/{start_date}/{end_date}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get account details by ID for authenticated user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of the account to retrieve
          required: true
          type: integer
        - in: path
          name: start_date
          description: Start date of transactions to fetch (YYYY-MM-DD)
          required: true
          type: string
        - in: path
          name: end_date
          description: End date of transactions to fetch (YYYY-MM-DD)
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Account retrieved successfully
          schema:
            $ref: '#/definitions/Account'
        '401':
          description: Unauthorized request
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Retrieve a specific transaction by ID
      description: |
        Retrieves the transaction with the specified ID.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction to retrieve
          required: true
          type: integer
      responses:
        '200':
          description: Returns the transaction with the specified ID
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized, authentication token is missing or invalid
        '403':
          description: Forbidden access
        '404':
          description: Transaction not found with the specified ID
      produces:
        - application/json
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update a specific transaction by ID
      description: |
        Updates Category and or Notes of the transaction with the specified ID.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction to update
          required: true
          type: integer
        - in: body
          name: body
          description: Transaction object containing updated information
          required: true
          schema:
            $ref: '#/definitions/TransactionInput'
      produces:
        - application/json
      responses:
        '200':
          description: Returns the updated transaction
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid request body
        '401':
          description: Unauthorized, authentication token is missing or invalid
        '404':
          description: Transaction not found with the specified ID
        '500':
          description: Internal Server Error
 
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string    
  Account:
    properties:
      id:
        type: integer
        description: account ID
      accountNumber:
        type: string
        description: account number
      accountType:
        type: string
        description: account type
      balance:
        type: number
        description: account balance
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'    
  TransactionsResponse:
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    properties:
      id:
        type: integer
        description: transaction ID
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: number
        description: transaction amount
      balance: 
        type: number
        description: account remaining balance  
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction notes  
      account:
        $ref: '#/definitions/Account'
        description: account related to the transaction
  TransactionInput:
    properties:
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction notes
  Bearer:
    type: string
    name: Authorization
    in: header
    description: Bearer JWT authentication token
